### ISSUE TITLE
Upgrade Laravel version

### ISSUE THREAD

**Issue by nbrabant** [nbrabant/rpi-inventory#18]
Actually, the project run on a old version of Laravel (7.x)

**Goals :** 
- upgrade to Laravel 9.x
- upgrade docker image for PHP
- update documentation

**Comment by dangenendt** [comment]
Hey.
I'd like to do that. ☝🏼

**Comment by nbrabant** [comment]
sure, you can :+1:

**Comment by dangenendt** [comment]
Nice!
Preferences for php version? 8.1, ay?

**Comment by nbrabant** [comment]
PHP 8.1 is ok for me

**Comment by dangenendt** [comment]
Application(s) work in general. There is just a problem with creating categories / products. 
The POST request leads to error 500 from backend as the CategoryData-Class tries to get the id of the unexisting entity (at this moment), at least it looks like it to me.
CategoryData uses:
`'id'        => $request->getId()`. which leads to the problem.
I wanted to debug this but xdebug is missing. Can i install it? This would be propbably helpful in future.

**Comment by nbrabant** [comment]
Hello and thanks for your feedback

Yep, I've reproduce the problem, I've miss that. It can be fixed in CategoryRequest|ProductRequest with typing return as nullable, you can fix it if you what :)

Sure, xdebug will be helpful in the future. Do you think you can enable or disable it on demand (just for the perf on local environnement)?

**Comment by dangenendt** [comment]
> Yep, I've reproduce the problem, I've miss that. It can be fixed in CategoryRequest|ProductRequest with typing return as nullable, you can fix it if you what :)

Yes, i will try that later. 

> Sure, xdebug will be helpful in the future. Do you think you can enable or disable it on demand (just for the perf on local environnement)
This will be possible 👍
