### ISSUE TITLE
[FRONT] Install translation module for vue-js

### ISSUE THREAD

**Issue by nbrabant** [nbrabant/rpi-inventory#27]
For i18n, the frontend must include translation functionalities

**Requirement :** 
- VueJs 2.5 compatibility

The first choice can be the [Vue I18n](https://kazupon.github.io/vue-i18n/) package
https://kazupon.github.io/vue-i18n/installation.html#direct-download-cdn

**Comment by dangenendt** [comment]
Can i do this?

**Comment by dangenendt** [comment]
@nbrabant 
This one can be closed
